name: ticktock
description: "This is TickTock, a clock to do app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  path: ^1.8.3
  intl: ^0.19.0
  timer_builder: ^2.0.0
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
